In [1]:
import pandas as pd

In [2]:
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [3]:
# show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### sample()
Parameter
* n	- Number of random rows to return
* frac	- Fraction (%) of rows to return
* replace	- Allow duplicate selection (True/False)
* random_state	- Fixed seed for same output every time

In [ ]:
df.sample(10,random_state=10)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
F. Ortega,Francisco Ortega,20,1999-03-19,177,75,Argentina,Vélez Sarsfield
M. Ilaimaharitra,Marco Ilaimaharitra,23,1995-07-26,177,79,Madagascar,Sporting de Charleroi
D. Parker,Devante Parker,23,1996-03-16,175,66,Germany,1. FSV Mainz 05
H. Mendoza,Humberto Antonio Mendoza Quiñónez,34,1984-10-02,189,85,Colombia,Envigado FC
K. Qaka,Kamer Qaka,24,1995-04-11,170,73,Albania,Universitatea Craiova
I. Hemans,Isaac Hemans,22,1996-12-26,168,64,Ghana,Paris Saint-Germain
A. Buziuc,Alexandru Buziuc,25,1994-03-15,174,75,Romania,Academica Clinceni
Kiko Olivas,Francisco José Olivas Alba,30,1988-08-21,184,76,Spain,Real Valladolid CF
T. Ogihara,扇原 貴宏,27,1991-10-05,184,71,Japan,Yokohama F. Marinos
L. Höler,Lucas Höler,24,1994-07-10,184,83,Germany,SC Freiburg

In [5]:
df.sample(5,random_state=10)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
F. Ortega,Francisco Ortega,20,1999-03-19,177,75,Argentina,Vélez Sarsfield
M. Ilaimaharitra,Marco Ilaimaharitra,23,1995-07-26,177,79,Madagascar,Sporting de Charleroi
D. Parker,Devante Parker,23,1996-03-16,175,66,Germany,1. FSV Mainz 05
H. Mendoza,Humberto Antonio Mendoza Quiñónez,34,1984-10-02,189,85,Colombia,Envigado FC
K. Qaka,Kamer Qaka,24,1995-04-11,170,73,Albania,Universitatea Craiova

In [8]:
# extract a random 20% sample of the dataframe
df.sample(frac=0.2,random_state=10)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
F. Ortega,Francisco Ortega,20,1999-03-19,177,75,Argentina,Vélez Sarsfield
M. Ilaimaharitra,Marco Ilaimaharitra,23,1995-07-26,177,79,Madagascar,Sporting de Charleroi
D. Parker,Devante Parker,23,1996-03-16,175,66,Germany,1. FSV Mainz 05
H. Mendoza,Humberto Antonio Mendoza Quiñónez,34,1984-10-02,189,85,Colombia,Envigado FC
K. Qaka,Kamer Qaka,24,1995-04-11,170,73,Albania,Universitatea Craiova
...,...,...,...,...,...,...,...
A. Koșelev,Alexei Koșelev,25,1993-11-19,200,90,Moldova,Fortuna Sittard
P. Ejimadu,Phillip Ejimadu,19,1999-08-31,188,98,United States,Los Angeles FC
E. List,Elliott List,22,1997-05-12,174,74,England,Gillingham
V. Bondarenko,Valeriy Bondarenko,25,1994-02-03,194,88,Ukraine,Vitória Guimarães
T. Chunchukov,Tsvetelin Chunchukov,24,1994-12-26,181,75,Bulgaria,Bulgaria

In [13]:
# df.sample(20000) ValueError: Cannot take a larger sample than population when 'replace=False'
df.sample(20000,replace=True)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
P. Kanstrup,Pierre Kanstrup,30,1989-02-21,188,81,Denmark,Vålerenga Fotball
J. White,Joe White,17,2002-01-18,188,72,England,Bolton Wanderers
D. Kılıç,Doğanay Kılıç,23,1996-06-08,177,72,Turkey,Göztepe SK
J. Fitzwater,Jack Fitzwater,21,1997-09-23,188,70,England,West Bromwich Albion
A. Fernández,Augusto Matías Fernández,33,1986-04-10,177,71,Argentina,Beijing Renhe FC
...,...,...,...,...,...,...,...
C. Pulisic,Christian Pulisic,20,1998-09-18,177,69,United States,Chelsea
M. Dembélé,Malaly Dembélé,22,1997-06-17,184,75,France,AS Nancy Lorraine
X. Schenk,Xandro Schenk,26,1993-04-28,187,88,Netherlands,FC Twente
D. Zapata,Duván Zapata,28,1991-04-01,189,88,Colombia,Atalanta
A. Quiñones,Angelo Quiñones,20,1998-07-20,175,73,Chile,Unión La Calera

In [15]:
# df.sample(frac=2) ValueError: Replace has to be set to `True` when upsampling the population `frac` > 1.
df.sample(frac=2,replace=True)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
J. Hopcutt,Jamie Hopcutt,27,1992-06-23,180,74,England,Östersunds FK
E. Pavez,Esteban Andres Pavez Suazo,29,1990-05-01,180,76,Chile,Chile
Y. Maziz,Youssef Maziz,21,1998-06-24,175,68,France,Le Mans FC
Yang Boyu,杨博宇,30,1989-06-24,185,81,China PR,Jiangsu Suning FC
D. Muringen,Dehninio Muringen,20,1999-02-01,186,80,Netherlands,ADO Den Haag
...,...,...,...,...,...,...,...
I. Powell,Izaack Powell,17,2002-02-12,173,70,Australia,Brisbane Roar
L. López,Luis López,25,1993-08-25,188,81,Mexico,FC Juárez
N. Córdova,Nelson Córdova,21,1998-03-31,172,70,Chile,Unión Española
I. Diallo,Ibrahima Diallo,20,1999-03-08,179,68,France,Stade Brestois 29
O. Solbakken,Ola Solbakken,20,1998-09-07,186,79,Norway,Ranheim Fotball